# Generated by Django 3.2.6 on 2021-12-27 14:14

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_Type_name', models.CharField(max_length=200, null=True, validators=[django.core.validators.MinLengthValidator(2)])),
                ('activity_Type_description', models.TextField(null=True)),
                ('activity_Type_img', models.FileField(upload_to='static/uploads')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_name', models.CharField(max_length=100)),
                ('activity_price', models.FloatField()),
                ('activity_img', models.FileField(upload_to='static/uploads')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('activity_Type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='resort.activity_type')),
            ],
        ),
    ]
