# Generated by Django 3.2.6 on 2022-01-05 15:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resort', '0002_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='activity_Type',
            new_name='activity_type',
        ),
        migrations.RenameField(
            model_name='activity_type',
            old_name='activity_Type_description',
            new_name='activity_type_description',
        ),
        migrations.RenameField(
            model_name='activity_type',
            old_name='activity_Type_img',
            new_name='activity_type_img',
        ),
        migrations.RenameField(
            model_name='activity_type',
            old_name='activity_Type_name',
            new_name='activity_type_name',
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resort.activity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
